services:
  api-auth:
    container_name: api-auth
    build:
      context: ./api-auth
    restart: always
    ports:
      - 3000:3000
    networks:
      - backend-auth
    depends_on:
      - db-psql


  db-psql:
    container_name: db-psql
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=c0tras3naS3gur@
      - POSTGRES_DB=tecsup
    networks:
      - backend-auth
    ports:
      - 5432:5432

  frontend:
    image: jaimehuacac/kanban_front:v1
    restart: always
    volumes:
      - ./env.ts:/src/app/src/environment/environment.ts
    ports:
      - 8000:8000
    networks:
      - backend-auth
    depends_on:
      - api-auth

networks:
  backend-auth: